feat: adiciona backend ao projeto
LrAmaral/smart_money pull request #8
Opened 2024-07-31 23:15 UTC by rafahcerqueira

Adicionando Back-end em NestJS ao projeto flutter.

2024-07-31 23:18 UTC, LrAmaral reviewed
👍🏽

2024-07-31 23:19 UTC, LrAmaral approved these changes
👍

2024-07-31 23:21 UTC, DanielAlmeidaToledo requested changes

2024-07-31 23:21 UTC, DanielAlmeidaToledo commented on backend/src/auth/models/UserPayload.ts
> +  sub: string;
O que é sub, iat e exp? deixar mais claro

2024-07-31 23:21 UTC, DanielAlmeidaToledo commented on backend/src/card/card.controller.ts
> +  //TODO: Implementar Decorator para que somente o admin possa acessar
esse TODO não vai ser implementado, certo?
Então remover do código

2024-07-31 23:21 UTC, DanielAlmeidaToledo commented on backend/src/card/card.controller.ts
Como não vamos usa cartões, pq não tirar parte de cards?

2024-07-31 23:21 UTC, DanielAlmeidaToledo commented on backend/src/transaction/transaction.controller.ts
> +  //TODO: Implementar Decorator para que somente o admin possa acessar
mesma coisa de um item acima

2024-07-31 23:38 UTC, rafahcerqueira commented on backend/src/auth/models/UserPayload.ts
> +  sub: string;
É um padrão do JWT de como o pessoal usa normalmente, que fica no payload da requisição, caso achem melhor podemos mudar, só que irá demorar um tempinho.

sub (subject) = Entidade à quem o token pertence, normalmente o ID do usuário;
exp (expiration) = Timestamp de quando o token irá expirar;
iat (issued at) = Timestamp de quando o token foi criado;

2024-08-01 00:14 UTC, DanielAlmeidaToledo approved these changes

2024-08-01 00:34 UTC, merged